name: Run CI
on:
  push:
    branches-ignore:
      - develop
      - release/**
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-2016, macos-latest, windows-2022 ]
        node: [ "12.0.0", "14.0.0", "15.0.0", "16.0.0", "17.0.0" ]
        task: [ test ]

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Configure msvs version on Windows
        if: ${{matrix.os == 'windows-2016'}}
        run: npm config set msvs_version 2017
      - name: Configure msvs version on Windows
        if: ${{matrix.os == 'windows-2022'}}
        run: npm config set msvs_version 2022
      - name: Run tests
        env:
          OPENCV4NODEJS_DISABLE_AUTOBUILD: 1
        run: |
          echo installing
          npm install --unsafe-perm
          echo running tests
          cd ./test
          npm install --unsafe-perm
          npm test
          npm run test-externalMemTracking
